### ISSUE TITLE
no case clause matching: :error in 2.13.3

### ISSUE THREAD

**Issue by woylie** [elixir-cldr/cldr_dates_times#36]
This works in ex_cldr_dates_times 2.13.2:

```
iex(1)> MyAppWeb.Cldr.Date.Interval.to_string!(~D[2022-11-19], ~D[2022-12-11], format: :medium)
"2022年11月19日～12月11日"
```

However, in version 2.13.3, I'm getting this:

```
iex(1)> MyAppWeb.Cldr.Date.Interval.to_string!(~D[2022-11-19], ~D[2022-12-11], format: :medium)
** (CaseClauseError) no case clause matching: :error
    (ex_cldr_dates_times 2.13.3) lib/cldr/interval/date.ex:644: Cldr.Date.Interval.to_string!/4
```

ex_cldr version: 2.36.0

**Comment by kipcole9** [comment]
Ouch, that's not good. My apologies. Can you please confirm which locale is in effect? I'll work on this right away.

**Comment by woylie** [comment]
It's `ja`. But I'm not sure right now whether that's a bug indeed, or whether the compiler is just stubborn.

**Comment by woylie** [comment]
It seems to work now after deleting the `_build` folder.

**Comment by woylie** [comment]
I am on macOS, actually.

**Comment by kipcole9** [comment]
Arrrghhhh, that's even worse (from my perspective) since I do all my work on Macs and this has never been an issue for me other than on isolated Linux instances.  Would you mind pasting the configuration you have for `MyAppWeb.Cldr`?  I'm still trying to reproduce how on earth this can happen.

**Comment by woylie** [comment]
Sure, this is my backend module:

```
defmodule MyAppWeb.Cldr do
  @moduledoc false

  use Cldr,
    locales: ["ja", "en"],
    gettext: MyAppWeb.Gettext,
    otp_app: :my_app_web,
    providers: [Cldr.Calendar, Cldr.DateTime, Cldr.List, Cldr.Number, Cldr.Unit]
end
```
