### ISSUE TITLE
Question: what is a "number format definition"?

### ISSUE THREAD

**Issue by tjchambers** [elixir-cldr/cldr_dates_times#46]
This is referred to in the Compile module twice, without any explanation of what this is?

**Comment by kipcole9** [comment]
Thanks @tjchambers, I've updated the docs to be clearer.

**Comment by tjchambers** [comment]
Thanks - unfortunately there is a typo - Tpkenize s/b Tokenize

**Comment by kipcole9** [comment]
I've published [ex_cldr_dates_times version 2.18.0](https://hex.pm/packages/ex_cldr_dates_times/2.18.0) with the following changelog entry:

### Bug Fixes

* Clarify format compiler documentation. Thanks to @tjchambers for the issue. Closes #46.

* Fix typos. Thanks to @tjchambers for the PR. Closes #47.

Many thanks again.

**Comment by kipcole9** [comment]
Note that `ex_cldr_calendars` still needs Elixir 1.17 work to add the new callbacks which will take a few more days yet.
